import type { Filters, Job, RefreshResult, RegionInfo, SourceInfo } from "../types";

// Data is generated by the local script (scripts/generate_data.py) and served
// as static JSON from /data/ by Vercel — no backend to host.
const DATA = "/data";

// Keep letters/digits (Latin + Hebrew), drop spaces/hyphens/punctuation so
// "frontend", "front end" and "front-end" all match the same jobs.
function collapse(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9֐-׿]+/g, "");
}

/** Keep jobs where every word of the query appears in the title/excerpt. */
export function filterByKeyword(jobs: Job[], query: string): Job[] {
  const tokens = query
    .toLowerCase()
    .split(/[^a-z0-9֐-׿]+/i)
    .map(collapse)
    .filter(Boolean);
  if (tokens.length === 0) return jobs;
  return jobs.filter((j) => {
    const hay = collapse(`${j.title} ${j.excerpt}`);
    return tokens.every((tok) => hay.includes(tok));
  });
}

async function getJson<T>(path: string): Promise<T> {
  const resp = await fetch(path, { cache: "no-store" });
  if (!resp.ok) throw new Error(`HTTP ${resp.status} — ${resp.statusText}`);
  return resp.json() as Promise<T>;
}

export function getSources(): Promise<SourceInfo[]> {
  return getJson<SourceInfo[]>(`${DATA}/sources.json`);
}

export function getRegions(): Promise<RegionInfo[]> {
  return getJson<RegionInfo[]>(`${DATA}/regions.json`);
}

/**
 * Read a source's stored offers for a region, then filter by keyword (q)
 * client-side (files are per source+region; the keyword is applied here).
 */
export async function refreshSource(
  key: string,
  filters: Filters,
  _force = false,
): Promise<RefreshResult> {
  let data: RefreshResult;
  try {
    data = await getJson<RefreshResult>(`${DATA}/${key}__${filters.region}.json`);
  } catch {
    data = { source: key, count: 0, new_count: 0, jobs: [], cached: true };
  }

  const jobs = filterByKeyword(data.jobs, filters.q);

  return {
    source: key,
    count: jobs.length,
    new_count: jobs.filter((j) => j.is_new).length,
    jobs,
    cached: true,
  };
}
