import type { Job, RegionJobs, RegionInfo, SourceInfo } from "../types";

// Data is generated by the local script (scripts/generate_data.py) and served
// as static JSON from /data/ by Vercel — no backend. One file per region holds
// every source's jobs, so the app makes a single fetch per region.
const DATA = "/data";

async function getJson<T>(path: string): Promise<T> {
  const resp = await fetch(path, { cache: "no-store" });
  if (!resp.ok) throw new Error(`HTTP ${resp.status} — ${resp.statusText}`);
  return resp.json() as Promise<T>;
}

export function getSources(): Promise<SourceInfo[]> {
  return getJson<SourceInfo[]>(`${DATA}/sources.json`);
}

export function getRegions(): Promise<RegionInfo[]> {
  return getJson<RegionInfo[]>(`${DATA}/regions.json`);
}

/** All jobs (every source) for one region, in a single fetch. */
export async function getRegionJobs(region: string): Promise<Job[]> {
  try {
    const data = await getJson<RegionJobs>(`${DATA}/${region}.json`);
    return data.jobs;
  } catch {
    return [];
  }
}

// Keep letters/digits (Latin + Hebrew), drop spaces/hyphens/punctuation so
// "frontend", "front end" and "front-end" all match the same text.
function collapse(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9֐-׿]+/g, "");
}

/** Split a query into normalized tokens. */
export function queryTokens(query: string): string[] {
  return query
    .toLowerCase()
    .split(/[^a-z0-9֐-׿]+/i)
    .map(collapse)
    .filter(Boolean);
}

/** True if every query word appears in the given text. */
export function textMatches(text: string, tokens: string[]): boolean {
  if (tokens.length === 0) return true;
  const hay = collapse(text);
  return tokens.every((tok) => hay.includes(tok));
}

/** Keep jobs whose title/excerpt matches every word of the query. */
export function filterByKeyword(jobs: Job[], query: string): Job[] {
  const tokens = queryTokens(query);
  if (tokens.length === 0) return jobs;
  return jobs.filter((j) =>
    textMatches(`${j.title} ${j.excerpt} ${j.description ?? ""}`, tokens),
  );
}
